$type: Block
stmts:
- $type: Let
  name: cloudProvider
  e:
    $type: Nav
    obj:
      $type: Ref
      id: the customer request
    elems:
    - - cloudProvider
      - demo.config.CloudProvider
- $type: Let
  name: cluster
  e:
    $type: IfThenElse
    ifCond:
      $type: Nav
      obj:
        $type: Ref
        id: the customer request
      elems:
      - - mustHaveDedicatedEnv
        - Boolean
    thenVal:
      $type: DecisionApp
      funDef: demo.config.ZZZinferDedicatedCluster
      args:
      - - the customer request
        - $type: Ref
          id: the customer request
      body:
        $type: Block
        stmts:
        - $type: PModif
          left:
            $type: Nav
            obj:
              $type: Ref
              id: the customer request
            elems:
            - - ingress
              - Number
          right:
            $type: DLit
            v: 200
        e:
          $type: Obj
          ot: demo.config.DedicatedCluster
          mappings:
          - - minNumberOfNodes
            - $type: ILit
              v: 4
          id: []
    elseVal:
      $type: IfThenElse
      ifCond:
        $type: Nav
        obj:
          $type: Ref
          id: the customer request
        elems:
        - - mustHavePrivateEndpoints
          - Boolean
      thenVal:
        $type: IfThenElse
        ifCond:
          $type: Nav
          obj:
            $type: Ref
            id: the customer request
          elems:
          - - mustHaveSubSecondLatency
            - Boolean
        thenVal:
          $type: IfThenElse
          ifCond:
            $type: NComp
            l:
              $type: Nav
              obj:
                $type: Ref
                id: the customer request
              elems:
              - - ingress
                - Number
            op: Gt
            r:
              $type: ILit
              v: 600
          thenVal:
            $type: DecisionApp
            funDef: demo.config.ZZZinferDedicatedCluster
            args:
            - - the customer request
              - $type: Ref
                id: the customer request
            body:
              $type: Block
              stmts:
              - $type: PModif
                left:
                  $type: Nav
                  obj:
                    $type: Ref
                    id: the customer request
                  elems:
                  - - ingress
                    - Number
                right:
                  $type: DLit
                  v: 200
              e:
                $type: Obj
                ot: demo.config.DedicatedCluster
                mappings:
                - - minNumberOfNodes
                  - $type: ILit
                    v: 4
                id: []
          elseVal:
            $type: DecisionApp
            funDef: demo.config.ZZZinferEnterpriseCluster
            args:
            - - the customer request
              - $type: Ref
                id: the customer request
            body:
              $type: IfThenElse
              ifCond:
                $type: Nav
                obj:
                  $type: Ref
                  id: the customer request
                elems:
                - - includeOptionalComponent
                  - Boolean
              thenVal:
                $type: PMatch
                dependsOn:
                  $type: Nav
                  obj:
                    $type: Ref
                    id: the customer request
                  elems:
                  - - optionalComponent
                    - demo.config.OptionalComponent
                cases:
                - varName: optionA
                  $type: CaseType
                  type: demo.config.OptionA
                  value:
                    $type: Obj
                    ot: demo.config.EnterpriseCluster
                    mappings:
                    - - minNumberOfNodes
                      - $type: ILit
                        v: 7
                    - - capacity_of_a
                      - $type: Nav
                        obj:
                          $type: Ref
                          id: optionA
                        elems:
                        - - capacity
                          - demo.config.ZeroTo2400
                    id: []
                  whereOpt: []
                - whereOpt: []
                  $type: CaseType
                  varName: notification
                  value:
                    $type: Obj
                    ot: demo.config.EnterpriseCluster
                    mappings:
                    - - minNumberOfNodes
                      - $type: ILit
                        v: 6
                    - - notificationEmail
                      - $type: Nav
                        obj:
                          $type: Ref
                          id: notification
                        elems:
                        - - email
                          - demo.config.Email
                    id: []
                  type: demo.config.EmailNotification
                - $type: CaseType
                  whereOpt: []
                  type: demo.config.OptionB2
                  varName: optionB2
                  value:
                    $type: Obj
                    ot: demo.config.EnterpriseCluster
                    mappings:
                    - - minNumberOfNodes
                      - $type: ILit
                        v: 5
                    - - quantity_of_b2
                      - $type: Nav
                        obj:
                          $type: Ref
                          id: optionB2
                        elems:
                        - - quantity
                          - Integer
                    id: []
              elseVal:
                $type: Obj
                ot: demo.config.EnterpriseCluster
                mappings:
                - - minNumberOfNodes
                  - $type: ILit
                    v: 4
                id: []
        elseVal:
          $type: DecisionApp
          funDef: demo.config.ZZZinferFreightCluster
          args:
          - - the customer request
            - $type: Ref
              id: the customer request
          body:
            $type: Block
            stmts:
            - $type: Let
              name: fc
              e:
                $type: Obj
                ot: demo.config.FreightCluster
                mappings:
                - - minNumberOfNodes
                  - $type: ILit
                    v: 2
                id: []
            e:
              $type: Ref
              id: fc
      elseVal:
        $type: IfThenElse
        ifCond:
          $type: NComp
          l:
            $type: Nav
            obj:
              $type: Ref
              id: the customer request
            elems:
            - - ingress
              - Number
          op: Gt
          r:
            $type: ILit
            v: 250
        thenVal:
          $type: DecisionApp
          funDef: demo.config.ZZZinferEnterpriseCluster
          args:
          - - the customer request
            - $type: Ref
              id: the customer request
          body:
            $type: IfThenElse
            ifCond:
              $type: Nav
              obj:
                $type: Ref
                id: the customer request
              elems:
              - - includeOptionalComponent
                - Boolean
            thenVal:
              $type: PMatch
              dependsOn:
                $type: Nav
                obj:
                  $type: Ref
                  id: the customer request
                elems:
                - - optionalComponent
                  - demo.config.OptionalComponent
              cases:
              - type: demo.config.OptionA
                value:
                  $type: Obj
                  ot: demo.config.EnterpriseCluster
                  mappings:
                  - - minNumberOfNodes
                    - $type: ILit
                      v: 7
                  - - capacity_of_a
                    - $type: Nav
                      obj:
                        $type: Ref
                        id: optionA
                      elems:
                      - - capacity
                        - demo.config.ZeroTo2400
                  id: []
                whereOpt: []
                varName: optionA
                $type: CaseType
              - $type: CaseType
                value:
                  $type: Obj
                  ot: demo.config.EnterpriseCluster
                  mappings:
                  - - minNumberOfNodes
                    - $type: ILit
                      v: 6
                  - - notificationEmail
                    - $type: Nav
                      obj:
                        $type: Ref
                        id: notification
                      elems:
                      - - email
                        - demo.config.Email
                  id: []
                whereOpt: []
                type: demo.config.EmailNotification
                varName: notification
              - $type: CaseType
                value:
                  $type: Obj
                  ot: demo.config.EnterpriseCluster
                  mappings:
                  - - minNumberOfNodes
                    - $type: ILit
                      v: 5
                  - - quantity_of_b2
                    - $type: Nav
                      obj:
                        $type: Ref
                        id: optionB2
                      elems:
                      - - quantity
                        - Integer
                  id: []
                whereOpt: []
                varName: optionB2
                type: demo.config.OptionB2
            elseVal:
              $type: Obj
              ot: demo.config.EnterpriseCluster
              mappings:
              - - minNumberOfNodes
                - $type: ILit
                  v: 4
              id: []
        elseVal:
          $type: IfThenElse
          ifCond:
            $type: Nav
            obj:
              $type: Ref
              id: the customer request
            elems:
            - - isProductionUseCase
              - Boolean
          thenVal:
            $type: DecisionApp
            funDef: demo.config.ZZZinferStandardCluster
            args:
            - - the customer request
              - $type: Ref
                id: the customer request
            body:
              $type: Block
              stmts:
              - $type: Let
                name: subCapacities
                e:
                  $type: Map
                  collBType: List[demo.config.ZeroTo2400]
                  param: sc
                  functor:
                    $type: Nav
                    obj:
                      $type: Ref
                      id: sc
                    elems:
                    - - capacity
                      - demo.config.ZeroTo2400
                  coll:
                    actualTypeOpt:
                    - demo.config.SubComponent
                    filter:
                      $type: NativeFunApp
                      funDef: luego.text.startsWith
                      args:
                      - $type: Nav
                        obj:
                          $type: Ref
                          id: sc
                        elems:
                        - - code
                          - demo.config.SubComponentCode
                      - $type: SLit
                        s: A
                    coll:
                      $type: Nav
                      obj:
                        $type: Ref
                        id: the customer request
                      elems:
                      - - subComponents
                        - List[demo.config.SubComponent]
                    $type: Filter
                    param: sc
              - $type: Let
                name: numNodes
                e:
                  $type: NativeFunApp
                  funDef: luego.math.floorInt
                  args:
                  - $type: BinAr
                    l:
                      $type: Sum
                      type: Number
                      coll:
                        $type: Nav
                        obj:
                          $type: Ref
                          id: subCapacities
                        elems: []
                    op: Div
                    r:
                      $type: DLit
                      v: 10
              e:
                $type: Obj
                ot: demo.config.StandardCluster
                mappings:
                - - minNumberOfNodes
                  - $type: Ref
                    id: numNodes
                id: []
          elseVal:
            $type: DecisionApp
            funDef: demo.config.ZZZinferBasicCluster
            args:
            - - the customer request
              - $type: Ref
                id: the customer request
            body:
              $type: Obj
              ot: demo.config.BasicCluster
              mappings:
              - - minNumberOfNodes
                - $type: ILit
                  v: 2
              id: []
e:
  $type: Obj
  ot: demo.config.Configuration
  mappings:
  - - cluster
    - $type: Ref
      id: cluster
  - - cloudProvider
    - $type: Ref
      id: cloudProvider
  id: []
