e: '{"$type":"Block","stmts":[{"$type":"Let","name":"fc","e":{"$type":"Obj","ot":"demo.config.FreightCluster","mappings":[["minNumberOfNodes",{"$type":"ILit","v":2}]],"id":[]}}],"e":{"$type":"Ref","id":"fc"}}'
inputs:
- name: the customer request
  type: demo.config.CustomerRequest
output: demo.config.FreightCluster
imports:
- luego.text
- demo.config
