$type: Block
stmts:
- $type: PModif
  left:
    $type: Nav
    obj:
      $type: Ref
      id: the customer request
    elems:
    - - ingress
      - Number
  right:
    $type: DLit
    v: 200
e:
  $type: Obj
  ot: demo.config.DedicatedCluster
  mappings:
  - - minNumberOfNodes
    - $type: ILit
      v: 4
  id: []
