$type: IfThenElse
ifCond:
  $type: Nav
  obj:
    $type: Ref
    id: the customer request
  elems:
  - - includeOptionalComponent
    - Boolean
thenVal:
  $type: PMatch
  dependsOn:
    $type: Nav
    obj:
      $type: Ref
      id: the customer request
    elems:
    - - optionalComponent
      - demo.config.OptionalComponent
  cases:
  - value:
      $type: Obj
      ot: demo.config.EnterpriseCluster
      mappings:
      - - minNumberOfNodes
        - $type: ILit
          v: 7
      - - capacity_of_a
        - $type: Nav
          obj:
            $type: Ref
            id: optionA
          elems:
          - - capacity
            - demo.config.ZeroTo2400
      id: []
    $type: CaseType
    whereOpt: []
    type: demo.config.OptionA
    varName: optionA
  - value:
      $type: Obj
      ot: demo.config.EnterpriseCluster
      mappings:
      - - minNumberOfNodes
        - $type: ILit
          v: 6
      - - notificationEmail
        - $type: Nav
          obj:
            $type: Ref
            id: notification
          elems:
          - - email
            - demo.config.Email
      id: []
    type: demo.config.EmailNotification
    $type: CaseType
    whereOpt: []
    varName: notification
  - varName: optionB2
    value:
      $type: Obj
      ot: demo.config.EnterpriseCluster
      mappings:
      - - minNumberOfNodes
        - $type: ILit
          v: 5
      - - quantity_of_b2
        - $type: Nav
          obj:
            $type: Ref
            id: optionB2
          elems:
          - - quantity
            - Integer
      id: []
    type: demo.config.OptionB2
    whereOpt: []
    $type: CaseType
elseVal:
  $type: Obj
  ot: demo.config.EnterpriseCluster
  mappings:
  - - minNumberOfNodes
    - $type: ILit
      v: 4
  id: []
