---
imports:
  - luego.text.*
  - demo.config.*

output: Boolean
inputs:
  - name: the customer request
    type: demo.config.CustomerRequest

definition: >
  the ingress of `the customer request` is present
  and the optionalComponent of `the customer request` is present

###
exposable: false
description: Check if a member is present
usedDecisions: []
