---
imports:
  - luego.text.*
  - demo.config.*

output: demo.config.EnterpriseCluster
inputs:
  - name: the customer request
    type: demo.config.CustomerRequest
definition: >
  if `the customer request` includeOptionalComponent
  then
    depending on the optionalComponent of `the customer request` {
      case optionA: OptionA => EnterpriseCluster(minNumberOfNodes = 7, capacity_of_a = the capacity of optionA)
      case notification: EmailNotification =>
        EnterpriseCluster(minNumberOfNodes = 6, notificationEmail = the email of notification)
      case optionB2: OptionB2 =>
        EnterpriseCluster(minNumberOfNodes = 5, quantity_of_b2 = the quantity of optionB2)
    }
  else
      EnterpriseCluster(minNumberOfNodes = 4)

###
exposable: false
description: configure an enterprise Kafka cluster
usedDecisions: []
