---
imports:
  - luego.text.*
  - luego.math.*
  - demo.config.*

output: demo.config.StandardCluster
inputs:
  - name: the customer request
    type: demo.config.CustomerRequest
definition: >
  {
    let subCapacities = 
      for sc: SubComponent in the subComponents of `the customer request` where startsWith(sc.code, 'A') yield sc.capacity;
    let numNodes = floorInt(the sum of subCapacities / 10.0);
    StandardCluster(minNumberOfNodes = numNodes)
  } 

###
exposable: false
description: configure a standard Kafka cluster
usedDecisions: []
