$type: Block
stmts:
- $type: Let
  name: subCapacities
  e:
    $type: Map
    coll:
      coll:
        $type: Nav
        obj:
          $type: Ref
          id: the customer request
        elems:
        - - subComponents
          - List[demo.config.SubComponent]
      param: sc
      filter:
        $type: NativeFunApp
        funDef: luego.text.startsWith
        args:
        - $type: Nav
          obj:
            $type: Ref
            id: sc
          elems:
          - - code
            - demo.config.SubComponentCode
        - $type: SLit
          s: A
      actualTypeOpt:
      - demo.config.SubComponent
      $type: Filter
    param: sc
    collBType: List[demo.config.ZeroTo2400]
    functor:
      $type: Nav
      obj:
        $type: Ref
        id: sc
      elems:
      - - capacity
        - demo.config.ZeroTo2400
- $type: Let
  name: numNodes
  e:
    $type: NativeFunApp
    funDef: luego.math.floorInt
    args:
    - $type: BinAr
      l:
        $type: Sum
        type: Number
        coll:
          $type: Nav
          obj:
            $type: Ref
            id: subCapacities
          elems: []
      op: Div
      r:
        $type: DLit
        v: 10
e:
  $type: Obj
  ot: demo.config.StandardCluster
  mappings:
  - - minNumberOfNodes
    - $type: Ref
      id: numNodes
  id: []
